# Generated by Django 4.1 on 2023-09-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_email",
            field=models.EmailField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
