# Generated by Django 4.1 on 2023-09-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0002_customer_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ips",
            name="address",
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
